[package]
name = "syncshare"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version = "0.5.16", features = ["headers"]}
tokio = {version = "1.21.1", features = ["full"]}
serde = {version = "1.0.145", features = ["derive"]}
serde_json = "1.0.85"
dotenv = "0.15.0"
futures = "0.3.24"
simple_logger = "2.3.0"

[dependencies.tower-http]
version = "*"
features = ["cors"]
