[package]
version = "0.1.0"
name = "hugsqlx-analyzer"
edition = "2021"

[lib]

[dependencies]
syn = {version = "1", default-features = false, features = ["derive", "parsing", "proc-macro"]}
proc-macro2 = "1"
quote = "1"
chumsky = "0.8.0"
walkdir = "2.3.2"
